### ISSUE TITLE
No module named metric_learn

### ISSUE THREAD

**Issue by pby5** [Cysu/open-reid#23]
thanks for your work, when I use softmax example, I find this error"Traceback (most recent call last):
  File "softmax_loss.py", line 12, in <module>
    from reid import datasets
  File "/home/yuepan/code/pytorch_open_reid/reid/__init__.py", line 7, in <module>
    from . import metric_learning
  File "/home/yuepan/code/pytorch_open_reid/reid/metric_learning/__init__.py", line 3, in <module>
    from metric_learn import (ITML_Supervised, LMNN, LSML_Supervised,
ImportError: No module named metric_learn"
and I find no metric_learn.py in folder

**Comment by zydou** [comment]
You should install metric-learn first.
```
pip install metric-learn
```

**Comment by pby5** [comment]
thx

**Comment by Cysu** [comment]
@zydou Thank you very much!
