### ISSUE TITLE
ValueError: num_val exceeds total identities 0

### ISSUE THREAD

**Issue by raviks789** [Cysu/open-reid#73]
Hi,

I keep getting the below error when I try to run triplet_loss.py. The script is run as following:

> _**python examples/triplet_loss.py -d dukemtmc -b 64 -j 2 -a resnet50 --combine-trainval --lr .0003 --logs-dir logs/triplet-loss/dukemtmc-resnet50**_

Traceback (most recent call last):
  File "examples/triplet_loss.py", line 220, in <module>
    main(parser.parse_args())
  File "examples/triplet_loss.py", line 92, in main
    args.combine_trainval)
  File "examples/triplet_loss.py", line 29, in get_data
    dataset = datasets.create(name, root, split_id=split_id)
  File "/media/newhome/open_reid_sample/examples/reid/datasets/__init__.py", line 45, in create
    return __factory[name](root, *args, **kwargs)
  File "/media/newhome/open_reid_sample/examples/reid/datasets/dukemtmc.py", line 23, in __init__
    self.load(num_val)
  File "/media/newhome/open_reid_sample/examples/reid/utils/data/dataset.py", line 54, in load
    .format(num))
ValueError: num_val exceeds total identities 0

Some one kindly help me out here.

**Comment by bhosalems** [comment]
Delete splis.json if you already had run the code once with some other errors, in my case it retained the previous files which were empty.
